apiVersion: apps/v1
kind: Deployment
metadata:
  name: finetuning-test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finetuning-test
  template:
    metadata:
      labels:
        app: finetuning-test
    spec:
      containers:
        - name: albert-finetuning-container
          image: albert-finetuning-job-minikube:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: albert-finetuning-service
spec:
  selector:
    app: finetuning-test