name: Deploy Docs

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install sphinx

      - name: Build documentation
        run: |
          make -C docs html

      - name: Deploy to gh-pages
        run: |
          # Certifique-se de que você tem uma cópia atualizada da branch remota
          git fetch origin gh-pages
          
          # Certifique-se de estar no branch gh-pages
          git checkout gh-pages
          
          # Crie um diretório temporário para os arquivos HTML
          mkdir temp-html
          
          # Copie apenas os arquivos HTML gerados para o diretório temporário
          cp -r docs/build/html/* temp-html/
          
          # Limpe o conteúdo atual da branch gh-pages
          git rm -r ./*
          
          # Copie os arquivos HTML do diretório temporário para a branch gh-pages
          cp -r temp-html/* ./
          
          # Adicione os novos arquivos
          git add .
          
          # Configure o nome e email do usuário para o commit
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          
          # Faça um commit com a mensagem apropriada
          git commit -m "Update documentation"
          
          # Faça push das alterações para a branch gh-pages
          git push origin gh-pages
